### ISSUE TITLE
Error while 'Collecting wiki contributors' from phpdocbrbridge/traducao

### ISSUE THREAD

**Issue by rogeriopradoj** [LABHR/octohatrack#81]
Hello, @glasnt!

I got this error in v0.5.0 while using trying to run `octohatrack` against <https://github.com/phpdocbrbridge/traducao>.

## via pip installed version on OS X
```
$ octohatrack --version

octohatrack version 0.5.0

$ octohatrack phpdocbrbridge/traducao

Collecting API contributors...
Collecting all repo contributors...
Collecting wiki contributors.....'ascii' codec can't encode character u'\xe1' in position 1: ordinal not in range(128)
```

## via Docker

```
$ docker run \
    --interactive \
    --tty \
    --rm \
    --env GITHUB_TOKEN=$GITHUB_TOKEN \
    --volume $HOME/.octohatrack:/cache \
     \
    rogeriopradoj/octohatrack:latest \
    \
     --version

octohatrack version 0.5.0

$ docker run \
    --interactive \
    --tty \
    --rm \
    --env GITHUB_TOKEN=$GITHUB_TOKEN \
    --volume $HOME/.octohatrack:/cache \
     \
    rogeriopradoj/octohatrack:latest \
    \
     phpdocbrbridge/traducao

Collecting API contributors...
Collecting all repo contributors...
Collecting wiki contributors....Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/git/cmd.py", line 614, in execute
    **subprocess_kwargs
  File "/usr/local/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/octohatrack", line 9, in <module>
    load_entry_point('octohatrack==0.5.0', 'console_scripts', 'octohatrack')()
  File "/usr/local/lib/python3.5/site-packages/octohatrack/__init__.py", line 50, in main
    wiki_contributors = get_wiki_contributors(repo_name)
  File "/usr/local/lib/python3.5/site-packages/octohatrack/wiki.py", line 54, in get_wiki_contributors
    repo = Repo.clone_from(wiki_url, tmp_folder)
  File "/usr/local/lib/python3.5/site-packages/git/repo/base.py", line 957, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/git/repo/base.py", line 898, in _clone
    v=True, **add_progress(kwargs, git, progress))
  File "/usr/local/lib/python3.5/site-packages/git/cmd.py", line 459, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/git/cmd.py", line 920, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/usr/local/lib/python3.5/site-packages/git/cmd.py", line 617, in execute
    raise GitCommandNotFound(str(err))
git.exc.GitCommandNotFound: [Errno 2] No such file or directory: 'git'

```

**Comment by glasnt** [comment]
Thank you for the detailed report! I'll have a look into it.

**Comment by glasnt** [comment]
Ok, the first one is an encoding error. My bad, I'll get that fixed. 

The second is docker not having git in the container. That'll be an oversight of me not adding it to the dockerfile. Once that's changed, your docker image will require updating. 

Hang tight, I'll get them fixed as soon as I can

**Comment by rogeriopradoj** [comment]
Oh, thanks for the quick reply!

The first one, working with ruby is not for me (yet!).

The second, docker, I'm sending a Pull Request with that!

Thanks!

**Comment by rogeriopradoj** [comment]
> The first one, working with ruby is not for me (yet!).

Oops, working with python!

**Comment by glasnt** [comment]
@rogeriopradoj I think the first one python2.7 related. Octohatrack uses some python-3 only commands, and thus can't run in 2.7

Can you confirm by running `python --version` on your system?

I'm looking into ways I can force python3 in the package installation.

**Comment by glasnt** [comment]
I've released version 0.5.1 which should work for at least failing nicely for the wiki things. The change to the Dockerfile is in there as well, you'll just have to copy the new `RUN apt-get` statement

**Comment by rogeriopradoj** [comment]
On OS X:
```
$ python --version

Python 2.7.11
```

P.S.: I just seen right know that #82 was already merged! Thanks!

**Comment by rogeriopradoj** [comment]
And:

```
$ pip --version
pip 8.1.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

So I think I'll have to install with `pip3` as you suggested:
```
$ pip3 --version
pip 8.0.2 from /usr/local/lib/python3.5/site-packages (python 3.5)
```

**Comment by rogeriopradoj** [comment]
Solved for pip3 installed octohatrack v0.5.1 on OS X!

```
$ octohatrack phpdocbrbridge/traducao
Collecting API contributors...
Collecting all repo contributors...
Collecting wiki contributors.....Collecting CONTRIBUTORS file...No CONTRIBUTORS file

GitHub Contributors:
alfsb
dtgfranca (Diego França)
fabioluciano (Fábio Luciano)
invalid-email-address (Check your git settings!)
matheusmmo (Matheus Moraes)

All Contributors:
alfsb
dtgfranca (Diego França)
fabioluciano (Fábio Luciano)
Fábio Luciano
giordanolins (Giordano Lins)
invalid-email-address (Check your git settings!)
matheusmmo (Matheus Moraes)
pojda
Rogerio Prado de Jesus
rogeriopradoj (Rogerio Prado de Jesus)
tassoevan (Tasso Evangelista)

Repo: phpdocbrbridge/traducao
GitHub Contributors: 5
All Contributors: 11
```

**Comment by glasnt** [comment]
Hooray! 🎉 I'm glad it's working

Thank you so much for filing the bug!

**Comment by rogeriopradoj** [comment]
Solved as well in Docker!

```
docker run \
        --interactive \
        --tty \
        --rm \
        --env GITHUB_TOKEN=${GITHUB_TOKEN} \
        --volume ${HOME}/.octohatrack:/cache \
        \
        rogeriopradoj/octohatrack:latest \
        \
        phpdocbrbridge/traducao
Collecting API contributors...
Collecting all repo contributors...
Collecting wiki contributors.....Collecting CONTRIBUTORS file...No CONTRIBUTORS file

GitHub Contributors:
alfsb
dtgfranca (Diego França)
fabioluciano (Fábio Luciano)
invalid-email-address (Check your git settings!)
matheusmmo (Matheus Moraes)

All Contributors:
alfsb
dtgfranca (Diego França)
fabioluciano (Fábio Luciano)
Fábio Luciano
giordanolins (Giordano Lins)
invalid-email-address (Check your git settings!)
matheusmmo (Matheus Moraes)
pojda
Rogerio Prado de Jesus
rogeriopradoj (Rogerio Prado de Jesus)
tassoevan (Tasso Evangelista)

Repo: phpdocbrbridge/traducao
GitHub Contributors: 5
All Contributors: 11
```

My pleasure to be one the contributors now! 😄
